name = "whereis"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[d1_databases]
DB = { binding = "DB", database_name = "whereis", database_id = "" }

[r2_buckets]
BUCKET = { binding = "BUCKET" }

[vars]
ENVIRONMENT = "production"
